### PR TITLE
cells/xschem/test: fix path

### LINKED ISSUE #90: incorrect symbol path in xschem tests
It seems that https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/24e721bd13601c1ff9983beec095e72dc333ab97/cells/xschem/tests/0_top.sch currently expect test symbols to be in a directory named `gf180mcu_tests`.

That directory doesn't exist in https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/tree/24e721bd13601c1ff9983beec095e72dc333ab97/cells/xschem/tests.

### PR DESCRIPTION
**Pull request by proppy**
Fixes #90 

/cc @mithro @atorkmabrains

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM.

**Comment by mithro** [comment]
Merge if CI says yes?

**Comment by proppy** [comment]
I'd like @atorkmabrains to ACK too.

**Comment by atorkmabrains** [comment]
LGTM @proppy

**Pull request merged**
