### PR TITLE
Fix units for AS and AD to be square microns

### PR DESCRIPTION
**Pull request by GlenHertz**
W and L are in microns, therefore AS and AD should be in square microns.  Currently they are in microns.

### CODE REVIEW

**Comment by QuantamHD** [comment]
What do AS and AD stand for in this context?

**Comment by GlenHertz** [comment]
AS = Area of Source 
AD = Area of Drain

The W and L and other dimensions are in microns so when you multiply W*L the units should be 1e-12 meters (not 1e-6) as in the file.

**Comment by RTimothyEdwards** [comment]
@QuantamHD :  AS = area of source, AD = area of drain, PS = perimeter of source, PD = perimeter of drain.  These are standard parameters for every MOSFET device in SPICE.

I can vouch for this pull request.  The script `models_regression.py` is using width values in microns, and the area is defined in the script as the width * 0.24, where 0.24 must also be in microns;  therefore the numbers must be converted to SI units for ngspice.  Linear values like perimeter must be multiplied by 1E-6 or use the "u" suffix, and squared values like area must be multiplied by (1E-6 * 1E-6) = 1E-12 or use the "p" suffix.

**Review by RTimothyEdwards — APPROVED** [review]
This fix is correct and needs to be applied.

**Comment by GlenHertz** [comment]
I haven't really looked but there may be other places where this same error is happening.

**Comment by QuantamHD** [comment]
Okay once CI passes will merge.

**Pull request merged**
