### PR TITLE
Fix CI actions to make them run and update against Ubuntu.

### LINKED ISSUE #23: Merging #17 broke the CI
@mohanad0mohamed - Looks like merging this pull request broke the CI - see https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/actions - can you please investigate.

_Originally posted by @mithro in https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/17#issuecomment-1210037571_

### PR DESCRIPTION
**Pull request by atorkmabrains**
Fixes #23:
Added commands to update the version of Ubuntu in the CI actions to allow proper installation of Klayout.

- [ ] Tests pass

### CODE REVIEW

**Review by mithro — APPROVED** [review]
Will merge if the pull request goes green.

**Comment by atorkmabrains** [comment]
@mithro ok.

**Comment by mithro** [comment]
I'm going to merge this on the assumption that the last test will succeed.

**Comment by atorkmabrains** [comment]
Thanks @mithro

**Pull request merged**
