### PR TITLE
rules/klayout/lvs: parse xschem netlist

### LINKED ISSUE #98: lvs script should be able to read X subcircuit
## Expected Behavior

https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/main/rules/klayout/lvs/gf180mcu.lvs doesn't seem to be able to parse `X` subcircuit in the following netlist:
```
.subckt TOP VP VN Y A
X1 Y A VP VP pfet_03v3 L=0.28u W=0.22u nf=1 
X2 Y A VN VN nfet_03v3 L=0.28u W=0.22u nf=1 
.ends
```

## Actual Behavior

klayout shows an empty circuit:
image

## Implementation suggestion / workaround

https://klayout.de/doc-qt4/manual/lvs_io.html#h2-146 mentions that:
> Only a subset of elements is implemented by default. These are "M" (gives "MOS4" device classes), "Q" (gives BJT3 or BJT4 device classes), "R" (gives Resistor device classes), "C" (gives Capacitor device classes) and "D" (gives diode device classes).

and provide a `NetlistSpiceReaderDelegate` to implement subcircuit parsing:
```
# Provides a SPICE netlist reader delegate which turns
# some subcircuit models (for subcircuits NMOS and PMOS)
# into devices

class SubcircuitModelsReader < RBA::NetlistSpiceReaderDelegate

  # implements the delegate interface:
  # says we want to catch these subcircuits as devices
  def wants_subcircuit(name)
    name == "NMOS" || name == "PMOS"
  end

  # implements the delegate interface: 
  # take and translate the element
  def element(circuit, el, name, model, value, nets, params)

    if el != "X"
      # all other elements are left to the standard implementation
      return super
    end

    if nets.size != 4
      error("Subcircuit #{model} needs four nodes")
    end

    # provide a device class
    cls = circuit.netlist.device_class_by_name(model)
    if ! cls
      cls = RBA::DeviceClassMOS4Transistor::new
      cls.name = model
      circuit.netlist.add(cls)
    end

    # create a device
    device = circuit.create_device(cls, name)

    # and configure the device
    [ "S", "G", "D", "B" ].each_with_index do |t,index|
      device.connect_terminal(t, nets[index])
    end

    # parameters in the model are given in micrometer units, so 
    # we need to translate the parameter values from SI to um values:
    device.set_parameter("W", (params["W"] || 0.0) * 1e6)
    device.set_parameter("L", (params["L"] || 0.0) * 1e6)

    return true

  end

end
```

We should consider integrate it with the existing `NetlistSpiceReaderDelegate` https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/main/rules/klayout/lvs/gf180mcu.lvs#L151-L248

### PR DESCRIPTION
**Pull request by proppy**
- try multiple extension
- remove modeling equations
- parse X subckt elements
- reorder device signals

Fixes #98 #101

### CODE REVIEW

**Comment by atorkmabrains** [comment]
@proppy I advise against making this change in LVS. The LVS deal with X as subcircuit by default not as primitive. adding the device as X might lead to weird behavior in LVS.

**Comment by atorkmabrains** [comment]
@proppy Usually, the netlist for simulation use X for devices, but when you create a netlist for LVS purpose, it should use the primitive form of that device like: M, L, R, Q, etc...

**Comment by atorkmabrains** [comment]
The solution for that should happen in side `xschem` or any other tool that generates the netlist. LVS should only use primitive form for devices and `X` for real subcircuits that present a circuit not a device. Remember the purpose of LVS it check the equivalence of the circuit against layout not to simulate the netlist.

**Comment by atorkmabrains** [comment]
I believe @StefanSchippers has already addressed that #102.

Please don't change the LVS rule deck. It's working correctly.

**Comment by proppy** [comment]
> @proppy I advise against making this change in LVS. The LVS deal with X as subcircuit by default not as primitive. adding the device as X might lead to weird behavior in LVS.

Yes, I agree with https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/102 the primitive gets correctly exported as `M` devices with the right pin ordering so I don't believe 94ae36839f6348f38b21392c702f940033cf1a0d is necessary anymore.

**Comment by proppy** [comment]
> Please don't change the LVS rule deck. It's working correctly.

I still believe that the part of https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/99/commits/061d37665aa032c6627b4f3aba412385968f90e2#diff-5692c889f49e046ff484fad52b83b49f9adfd5f9f8258289418462282a350f2bR290-R296 that deals with multiple file extension could be useful for interactive usage.

What do you think?

**Comment by atorkmabrains** [comment]
I don't believe file extension is important for `klayout`. As long as the file adhere with the `Standard Spice Format` with the limitation mentioned here:
https://klayout.de/doc-qt4/manual/lvs_io.html#h2-146

**Comment by atorkmabrains** [comment]
@proppy The LVS: 
https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/tree/main/rules/klayout/lvs 
is working correctly. If there are differences between what we have there and here in Google's version, I would advise that you take Efabless version.

**Comment by proppy** [comment]
> I don't believe file extension is important for klayout.

Yes, but the default produced by xschem (`.spice`) doesn't match with the default consumed by the lvs deck (`.cdl`).
https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/main/rules/klayout/lvs/gf180mcu.lvs#L259

**Comment by atorkmabrains** [comment]
@proppy I get the point, we could change `.cdl` to `.spice` in the LVS.

**Comment by proppy** [comment]
@atorkmabrains yes, see https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/26

**Pull request closed without merging**
