### PR TITLE
homogenize testing target names

### PR DESCRIPTION
**Pull request by umarcor**
Extracted from https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/18#discussion_r942704845.

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM!

**Comment by mithro** [comment]
Will merge this pull request once we get a green CI.

**Comment by umarcor** [comment]
Now ~based on #29~ ready to merge.

**Review by mithro — APPROVED** [review]
LGTM! Will merge if CI goes green.

**Pull request merged**
