### PR TITLE
Change colors to be more accepted values.

### PR DESCRIPTION
**Pull request by mguthaus**
The previous colors were randomly assigned. These are similar to other technologies.

### CODE REVIEW

**Comment by QuantamHD** [comment]
Would you mind pasting in a screen shot of the before and after for posterity. Otherwise LGTM

**Comment by mguthaus** [comment]
old colors

new colors

**Comment by QuantamHD** [comment]
@mithro looks like the CI is broken because it's trying to install qt5-default which is no longer distributed by debian.

**Comment by QuantamHD** [comment]
@mguthaus I'll merge this anyway since it's a visual only change.

**Pull request merged**
