### PR TITLE
DRC/LVS updates to improve performance

### PR DESCRIPTION
**Pull request by atorkmabrains**
Enhances #56 

The following updates were done to make the code runs faster:
- Changing some of the slow commands in Klayout with faster ones.
- Split the rule deck into tables and run each of them in parallel using the python script.
- Fix to R comparison in LVS.

### CODE REVIEW

**Comment by mithro** [comment]
This needs to be rebased onto master.

**Comment by mithro** [comment]
@atorkmabrains - This pull request needs a better description on how you improve the performance of the DRC/LVS.

**Comment by atorkmabrains** [comment]
@mithro Done. I have updated the description.

**Review by mithro — COMMENTED** [review]
@atorkmabrains All the new `.drc` files where missing license headers. They also had a bunch of trailing whitespace. I have fixed these issues and updated this pull request.

Will merge if the CI goes green.

**Pull request merged**
